# Generated by Django 5.1.3 on 2024-11-14 13:18

import django.db.models.deletion
import pyuploadcare.dj.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(blank=True, default='', max_length=200, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=10000)),
                ('car_type', models.CharField(blank=True, default='', max_length=200)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('dealer', models.CharField(blank=True, default='', max_length=200)),
                ('logo', pyuploadcare.dj.models.ImageField(blank=True, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', pyuploadcare.dj.models.ImageField()),
                ('image_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='CAR.carmodel')),
            ],
        ),
    ]
