# Generated by Django 5.1.3 on 2024-11-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
