# Generated by Django 5.1.3 on 2024-11-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0002_carmodel_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='image',
        ),
    ]
