# Generated by Django 5.1.3 on 2024-11-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0003_remove_carimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='logo',
        ),
    ]
