# Generated by Django 5.1.3 on 2024-11-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0004_remove_carmodel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
