# Generated by Django 5.1.3 on 2024-11-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0006_carmodel_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_name',
            field=models.CharField(max_length=200),
        ),
    ]
